# code is not ready for C++17, which GCC 11 / clang 16 defaults to
c_compiler_version:     # [unix]
  - 10                  # [linux]
  - 15                  # [osx]
cxx_compiler_version:   # [unix]
  - 10                  # [linux]
  - 15                  # [osx]
