{% set name = "source-highlight" %}
{% set version = "3.1.9" %}
{% set sha256 = "3a7fd28378cb5416f8de2c9e77196ec915145d44e30ff4e0ee8beb3fe6211c91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/src-highlite/source-highlight-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - boost-cpp
    - libtool
    - texinfo
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}

test:
  commands:
    - source-highlight --help

about:
  home: https://www.gnu.org/software/src-highlite/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'This program, given a source file, produces a document with syntax highlighting.'
  doc_url: https://www.gnu.org/software/src-highlite/source-highlight.html
  dev_url: http://git.savannah.gnu.org/cgit/src-highlite.git

extra:
  recipe-maintainers:
    - carlodri
    - scopatz
    
