schema_version: 1

context:
  version: 3.1.9

package:
  name: source-highlight
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/src-highlite/source-highlight-${{ version }}.tar.gz
  sha256: 3a7fd28378cb5416f8de2c9e77196ec915145d44e30ff4e0ee8beb3fe6211c91

build:
  number: 9
  skip: win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - autoconf
    - automake
    - gettext-tools
    - if: build_platform != target_platform
      then: libboost-devel
    - make
    - sed
    - texinfo
  host:
    - libboost-devel
    - libtool

tests:
  - script:
      - source-highlight --help

about:
  license: GPL-3.0-only
  license_file: COPYING
  summary: This program, given a source file, produces a document with syntax highlighting.
  homepage: https://www.gnu.org/software/src-highlite/
  repository: http://git.savannah.gnu.org/cgit/src-highlite.git
  documentation: https://www.gnu.org/software/src-highlite/source-highlight.html

extra:
  recipe-maintainers:
    - danielnachun
    - carlodri
    - scopatz
